version: '2'

services:
  db:
    image: postgres:9.6.1
    volumes:
    - postgres_data:/var/lib/postgresql/data

  puma:
    build:
      context: .
    command: bundle exec puma --config config/puma.rb
    environment:
    - RAILS_ENV=development
    - PORT=3000
    volumes:
    - .:/app
    - bundle_install:/app/vendor/bundle
    - bundle:/app/.bundle
    ports:
    - 3000:3000
    depends_on:
    - db

  yarn:
    build:
      context: ./client
    command: yarn run watch
    volumes:
    - ./client:/app
    - ./public/assets:/app/dist
    - node_modules:/app/node_modules
    - flow-typed:/app/flow-typed

volumes:
  postgres_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
  flow-typed:
    driver: local
